services:
  - type: web
    name: servd-strapi-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_SSL
        value: "true"
      - key: DATABASE_PORT
        value: "5432"
